import { addIcons } from 'ionicons';
import {
  personOutline,
  personCircleOutline,
  mailOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  carSportOutline,
  calendarOutline,
  walletOutline,
  homeOutline,
  homeSharp,
  listOutline,
  settingsOutline,
  settingsSharp,
  logOutOutline,
  starOutline,
  star,
  checkmarkCircle,
  checkmarkCircleOutline,
  closeOutline,
  closeCircle,
  arrowBackOutline,
  searchOutline,
  optionsOutline,
  addOutline,
  addCircleOutline,
  cardOutline,
  cashOutline,
  giftOutline,
  locationOutline,
  timeOutline,
  shieldCheckmarkOutline,
  helpCircleOutline,
  helpCircleSharp,
  informationCircleOutline,
  chevronForwardOutline,
  chevronBackOutline,
  peopleOutline,
  flashOutline,
  speedometerOutline,
  batteryChargingOutline,
  trendingUpOutline,
  trendingDownOutline,
  downloadOutline,
  shareSocialOutline,
  pricetagOutline,
  ticketOutline,
  alertCircleOutline,
  warningOutline,
  callOutline,
  chatbubbleEllipsesOutline,
  documentTextOutline,
  logoGoogle,
  fingerPrintOutline,
  carOutline,
  bicycleOutline,
  busOutline,
  boatOutline,
  bicycle,
  ribbonOutline,
  receiptOutline,
  walletSharp,
  personSharp,
  personCircle,
  createOutline,
  chevronDownOutline,
  chevronUpOutline,
  refreshOutline,
  medkitOutline,
  accessibilityOutline,
  sparklesOutline,
  arrowForwardOutline,
  menuOutline,
} from 'ionicons/icons';

export function registerIcons(): void {
  addIcons({
    'person-outline': personOutline,
    'person-circle-outline': personCircleOutline,
    'person-circle': personCircle,
    'person-sharp': personSharp,
    'mail-outline': mailOutline,
    'lock-closed-outline': lockClosedOutline,
    'eye-outline': eyeOutline,
    'eye-off-outline': eyeOffOutline,
    'car-sport-outline': carSportOutline,
    'car-outline': carOutline,
    'calendar-outline': calendarOutline,
    'wallet-outline': walletOutline,
    'wallet-sharp': walletSharp,
    'home-outline': homeOutline,
    'home-sharp': homeSharp,
    'list-outline': listOutline,
    'settings-outline': settingsOutline,
    'settings-sharp': settingsSharp,
    'log-out-outline': logOutOutline,
    'star-outline': starOutline,
    star,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'close-outline': closeOutline,
    'close-circle': closeCircle,
    'arrow-back-outline': arrowBackOutline,
    'arrow-forward-outline': arrowForwardOutline,
    'menu-outline': menuOutline,
    'search-outline': searchOutline,
    'options-outline': optionsOutline,
    'add-outline': addOutline,
    'add-circle-outline': addCircleOutline,
    'card-outline': cardOutline,
    'cash-outline': cashOutline,
    'gift-outline': giftOutline,
    'location-outline': locationOutline,
    'time-outline': timeOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'help-circle-outline': helpCircleOutline,
    'help-circle-sharp': helpCircleSharp,
    'information-circle-outline': informationCircleOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'chevron-back-outline': chevronBackOutline,
    'chevron-down-outline': chevronDownOutline,
    'chevron-up-outline': chevronUpOutline,
    'refresh-outline': refreshOutline,
    'people-outline': peopleOutline,
    'flash-outline': flashOutline,
    'speedometer-outline': speedometerOutline,
    'battery-charging-outline': batteryChargingOutline,
    'trending-up-outline': trendingUpOutline,
    'trending-down-outline': trendingDownOutline,
    'download-outline': downloadOutline,
    'share-social-outline': shareSocialOutline,
    'pricetag-outline': pricetagOutline,
    'ticket-outline': ticketOutline,
    'alert-circle-outline': alertCircleOutline,
    'warning-outline': warningOutline,
    'call-outline': callOutline,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    'document-text-outline': documentTextOutline,
    'logo-google': logoGoogle,
    'finger-print-outline': fingerPrintOutline,
    'bicycle-outline': bicycleOutline,
    'bus-outline': busOutline,
    'boat-outline': boatOutline,
    bicycle,
    'ribbon-outline': ribbonOutline,
    'receipt-outline': receiptOutline,
    'create-outline': createOutline,
    'medkit-outline': medkitOutline,
    'accessibility-outline': accessibilityOutline,
    'sparkles-outline': sparklesOutline,
  });
}
