create table if not exists public.claimed_reward_codes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reward_key text not null check (reward_key in ('reviewer', 'loyalty', 'weekend-warrior')),
  code text not null unique,
  discount_percent numeric(5, 2) not null check (discount_percent > 0 and discount_percent <= 100),
  description text not null,
  claimed_at timestamptz not null default now(),
  unique (user_id, reward_key)
);

alter table public.claimed_reward_codes enable row level security;

drop policy if exists "Users can read their own claimed rewards" on public.claimed_reward_codes;
create policy "Users can read their own claimed rewards"
  on public.claimed_reward_codes
  for select
  to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "Users can read their own reviews for reward progress" on public.reviews;
create policy "Users can read their own reviews for reward progress"
  on public.reviews
  for select
  to authenticated
  using (user_id = (select auth.uid()));

revoke all on public.claimed_reward_codes from anon, authenticated;
grant select on public.claimed_reward_codes to authenticated;

create or replace function public.claim_reward(reward_key_input text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  claimant_id uuid := auth.uid();
  required_count integer;
  qualifying_count integer;
  spend_total numeric;
  reward_discount numeric(5, 2);
  reward_description text;
  reward_code text;
begin
  if claimant_id is null then
    raise exception 'Sign in to claim rewards.';
  end if;

  case reward_key_input
    when 'reviewer' then
      select count(*)::integer
        into qualifying_count
        from public.reviews
        where user_id = claimant_id;
      required_count := 1;
      reward_discount := 10;
      reward_description := 'Review reward';
    when 'loyalty' then
      select coalesce(sum(total_price), 0)
        into spend_total
        from public.bookings
        where user_id = claimant_id
          and payment_status = 'completed'
          and booking_status <> 'cancelled';
      if spend_total < 5000 then
        raise exception 'Spend at least ₱5,000 on paid rentals to claim this reward.';
      end if;
      reward_discount := 12;
      reward_description := 'Loyalty milestone reward';
    when 'weekend-warrior' then
      select count(*)::integer
        into qualifying_count
        from public.bookings
        where user_id = claimant_id
          and payment_status = 'completed'
          and booking_status in ('confirmed', 'ongoing', 'completed')
          and extract(dow from pickup_date::date) in (0, 5, 6);
      required_count := 3;
      reward_discount := 15;
      reward_description := 'Weekend rental reward';
    else
      raise exception 'Unknown reward.';
  end case;

  if reward_key_input = 'reviewer' and qualifying_count < required_count then
    raise exception 'Submit a review before claiming this reward.';
  end if;
  if reward_key_input = 'weekend-warrior' and qualifying_count < required_count then
    raise exception 'Complete three paid weekend rentals before claiming this reward.';
  end if;

  insert into public.claimed_reward_codes (user_id, reward_key, code, discount_percent, description)
  values (
    claimant_id,
    reward_key_input,
    'SD-' || upper(replace(gen_random_uuid()::text, '-', '')),
    reward_discount,
    reward_description
  )
  on conflict (user_id, reward_key) do nothing;

  select code
    into reward_code
    from public.claimed_reward_codes
    where user_id = claimant_id
      and reward_key = reward_key_input;

  return jsonb_build_object('code', reward_code);
end;
$$;

revoke all on function public.claim_reward(text) from public, anon;
grant execute on function public.claim_reward(text) to authenticated;

notify pgrst, 'reload schema';
